// Included only by rustdoc tests with std. Keep all guide pages here so new Rust
// blocks on existing pages automatically join the normal `cargo test --doc` check.
#[doc = include_str!("../README.md")]
mod readme {}
#[doc = include_str!("../docs/src/introduction.md")]
mod introduction {}
#[doc = include_str!("../docs/src/getting-started.md")]
mod getting_started {}
#[doc = include_str!("../docs/src/core-concepts.md")]
mod core_concepts {}
#[doc = include_str!("../docs/src/eviction.md")]
mod eviction {}
#[doc = include_str!("../docs/src/ttl.md")]
mod ttl {}
#[doc = include_str!("../docs/src/concurrency.md")]
mod concurrency {}
#[doc = include_str!("../docs/src/api-reference.md")]
mod api_reference {}
#[doc = include_str!("../docs/src/api-raw.md")]
mod api_raw {}
#[doc = include_str!("../docs/src/api-typed.md")]
mod api_typed {}
#[doc = include_str!("../docs/src/api-concurrent.md")]
mod api_concurrent {}
#[doc = include_str!("../docs/src/api-sharded.md")]
mod api_sharded {}
#[doc = include_str!("../docs/src/api-entry.md")]
mod api_entry {}
#[doc = include_str!("../docs/src/architecture.md")]
mod architecture {}
#[doc = include_str!("../docs/src/benchmarks.md")]
mod benchmarks {}
#[doc = include_str!("../docs/src/features.md")]
mod features {}
#[doc = include_str!("../docs/src/ffi-bindings.md")]
mod ffi {}
#[doc = include_str!("../docs/src/embedded-no-std.md")]
mod embedded {}
#[doc = include_str!("../docs/src/use-cases.md")]
mod use_cases {}
#[doc = include_str!("../docs/src/faq.md")]
mod faq {}
#[doc = include_str!("../docs/src/contributing.md")]
mod contributing {}
#[doc = include_str!("../docs/src/changelog.md")]
mod changelog {}
